name: Terraform Destroy

on:
  workflow_dispatch:  # déploiement manuel

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Terraform Init
        run: terraform init -backend-config="access_key=${{ secrets.aws_access_key_id }}" \
                            -backend-config="secret_key=${{ secrets.aws_secret_access_key }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
          
      - name: Import existing resources
        run: |
          terraform import aws_db_subnet_group.private_db_subnet_group private_db_subnet_group
          terraform import aws_iam_policy.S3_policy arn:aws:iam::${{ secrets.aws_account_id }}:policy/WebAppS3
          terraform import aws_iam_role.lambda_s3_aurora lambda-s3
          terraform import aws_iam_policy.lambda_eni_policy arn:aws:iam::${{ secrets.aws_account_id }}:policy/eni_policy
          terraform import aws_rds_cluster.aurora_cluster serverless-cluster
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
      - name: Terraform Destroy (targeted)
        run: |
          terraform destroy -target=aws_db_subnet_group.private_db_subnet_group \
                      -target=aws_iam_policy.S3_policy \
                      -target=aws_iam_role.lambda_s3_aurora \
                      -target=aws_iam_policy.lambda_eni_policy \
                      -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
          
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
